config/routes.rb
Rails.application.routes.draw do
  get 'tasks/index'
  get 'tasks/:id/edit'=>'tasks#edit',
    as:"task_edit"
    post'tasks/:id/update'=>'task#update',
      as:"task_update"
  delete'task/:id/delete'=>'tasks#delete',
    as:"task_delete"
  post 'line/bot'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/line_controller.rb
require'line/bot'
class LineController<ApplicationController
    protect_form_forgery:except=>[:bot]
    def bot
        body=request.body.read
        signature=request.env['HTTP_X_LINE_SIGNATURE']
            unless client.validate_signature(body,signature)
            head:bad_request
            end
        
        events=client.parse_events_form(body)
        events.each{|event|
            case event
            when Line::Bot::Event::MessageType::Text
                case event.type
                    when Line::Bot::Event::MessageType::Text
                task=event['message']['text']
                begin
                Task.create!(task:task)
                message={
                    type:'text',
                    text: "タスク # {task} を登録しました!" }
                client.reply_message(event['replyToken'],message)
                rescue
                message={
                    type:'text',
                    text:"タスク # {task}の登録に失敗しました。"
                }
                client.reply_message(event['replyToken'],message)
                end
                end
            end
        }
        head:ok
    end
    
    private
    def client
        @client||=Line::Bot::Client.new{|config|
        config.channel_secret=
        ENV["LINE_CHANNEL_SECRET"]
        config.channel_token=
        ENV["LINE_CHANNEL_TOKEN"]
        }
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks=Task.all
  end
  
  def edit
    @task=Task.find(params[:id])
  end
  
  def update
    task=Task.find(params[:id])
    task.task=params[:task]
    if task.save
      redirect_to tasks_index_path,
        notice:"タスクを1件更新しました"
    else
      redirect_to tasks_index_path,
        alert:"タスクの更新に失敗しました"
    end
  end
  
  def delete
    task=Task.find(params[:id])
    if task.destroy
      redirect_to tasks_index_path,
        notice:"タスクを1件削除しました"
    else
      redirect_to tasks_index_path,
        alert:"タスクの削除に失敗しました"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%=stylesheet_pack_tag'application',
      media:'all','data-turbolinks-track':'reload'%>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%if notice.present? %>
      <aside class="alert alert-danger">
        <%=alert%>
      </aside>
      <%end%>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1 class="h4">タスク編集画面</h1>
<%=form_tag(task_update_path,method::post)do%>
    <div class="form-group">
        <%=text_area_tag:task,@task.task,
        class:'form-control'%>
    </div>
    <div class="action pb-5">
        <%=submit_tag '編集',
        class:'btn btn-primary'%>
        <%=link_to '一覧画面',tasks_index_path(@task),
        class:'btn btn-primary'%>
    </div>
    <%end%>

app/views/tasks/index.html.erb
<table class="table">
    <thread>
        <tr>
            <th class="h4">タスク</th>
        </tr>
    </thread>
    <tbody>
        <% @tasks.each do|task|%>
        <tr>
            <td><%=task.task%>
            </td>
            <td>
                <%=link_to '編集',task_edit_path(task)%>
            </td>
            <td>
                <%=link_to'削除',task_delete_path(task),
                method: :delete,
                    data:{confirm:'本当に削除しますか？'}
                %>
            </td>
        </tr>
        <%end%>
    </tbody>
</table>